version: '3'

services:
  postgres:
    container_name: postgres_cliente
    image: postgres
    environment:
      POSTGRES_DB: bantads-cliente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - cliente-network
    restart: always

  cliente:
    build: .
    image: bantads_cliente
    restart: on-failure
    container_name: bantads_cliente_container
    command: docker run -p 8080:8080 bantads_cliente
    volumes:
      - .:/app
      - static_data:/app/static
    networks:
      - cliente-network
      - rabbitmq
    ports:
      - "8280:8080"
    depends_on:
      - postgres

volumes:
  postgres:
  static_data:

networks:
  cliente-network:
    external: false
  rabbitmq:
    external: true